# Generated by Django 6.0.4 on 2026-04-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_image_lesson_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='progress',
            field=models.IntegerField(default=0, help_text='Progression en pourcentage (0-100)'),
        ),
    ]
