# Generated by Django 6.0.4 on 2026-04-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_enrollment_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='is_completed',
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
